algorithmType: 'yanhuodetect'
trackerType: 'bytetrack'
videosTask:
    videosId: '/home/ww/work/project/cross_line_area-master_new/cross_line_area-master_new/cross_line_area-master_new/video_data/值班室2_1218427.mp4'
    lines: [ ]
    areas:
      - - - 549
          - 573
        - - 1206
          - 627
        - - 0
          - 0
        - - 0
          - 0
      - - - 1191
          - 625
        - - 1514
          - 700
        - - 1343
          - 7114
        - - 1406
          - 609
    config:
      fps: 5
      alarm_last: 2
      alarm_interval: 10
      alarm_classes: ['fire']
topic: "AI_FIREWORKS_DETECTION"
kafka:
    kafkaIP: ['10.5.56.172:9092', '10.5.56.79:9092', '10.5.56.174:9092']
save:
    path: "/home/ww/work/project/triton_project/data"
commonConfig:
  fps: 25
  alarm_interval: 10
  # classes: ['vehicle']
