interfaceId: ''
algorithmType: 'crosslinedetect'
trackerType: 'bytetrack'
videosTask:
#    videosId: '/home/ww/work/project/triton_project/data/org_videos/helmet.mp4'
    videosId: 'https://open.ys7.com/v3/openlive/L31261130_3_1.m3u8?expire=1761815428&id=773595032161185792&t=d04788d5a6f8c7824259ac97d60ddd49ec437cc51f50b98e23d6a409b0ea7396&ev=100'
    lines:
      - - - 1146
          - 491
        - - 403
          - 1117
        - - 0
          - 0
        - - 0
          - 0

      - - - 500
          - 396
        - - 34
          - 841
        - - 728
          - 670
        - - 151
          - 525
    areas: []
    config:
      fps: 5
      alarm_last: 2
      alarm_interval: 10
      alarm_classes: ["worker","excavator","loader","dumptruck","truckcrane","crawlercrane",
                      "concretemixertruck","pumptruck","trailerpump","passengervehicle","rider","boxtruck","towercrane",
                      "roller","elevator","pc","pctruck","mixer","lighttruck","dozer","forklift","steel","pipe","panel","person"]
topic: "AI_CROSSLINE_IDENTIFICATION"
kafka:
    kafkaIP: ['10.5.56.172:9092', '10.5.56.79:9092', '10.5.56.174:9092']
save:
    path: "/home/ww/work/project/triton_project/data"
commonConfig:
  fps: 25
  alarm_interval: 10
  # classes: ['vehicle']
